In [1]:
import pandas as pd
import numpy as np

#  Data Collection

In [2]:
data=pd.read_csv("Raw data.csv")
data

,Country,Managed By,Fulfill Via,Vendor INCO Term,Shipment Mode,Product Group,Unit of Measure (Per Pack),Line Item Quantity,Line Item Value,Pack Price,Unit Price,First Line Designation,Weight (Kilograms),Freight Cost (USD),Line Item Insurance (USD)
0,Côte d'Ivoire,PMO - US,Direct Drop,EXW,Air,HRDT,30,19,551.00,29.00,0.97,Yes,13,780.34,NaN
1,Vietnam,PMO - US,Direct Drop,EXW,Air,ARV,240,1000,6200.00,6.20,0.03,Yes,358,4521.5,NaN
2,Côte d'Ivoire,PMO - US,Direct Drop,FCA,Air,HRDT,100,500,40000.00,80.00,0.80,Yes,171,1653.78,NaN
3,Vietnam,PMO - US,Direct Drop,EXW,Air,ARV,60,31920,127360.80,3.99,0.07,Yes,1855,16007.06,NaN
4,Vietnam,PMO - US,Direct Drop,EXW,Air,ARV,60,38000,121600.00,3.20,0.05,Yes,7590,45450.08,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
10319,Zimbabwe,PMO - US,From RDC,N/A - From RDC,Truck,ARV,60,166571,599655.60,3.60,0.06,No,See DN-4307 (ID#:83920),See DN-4307 (ID#:83920),705.79
10320,Côte d'Ivoire,PMO - US,From RDC,N/A - From RDC,Truck,ARV,60,21072,137389.44,6.52,0.11,No,See DN-4313 (ID#:83921),See DN-4313 (ID#:83921),161.71
10321,Zambia,PMO - US,From RDC,N/A - From RDC,Truck,ARV,30,514526,5140114.74,9.99,0.33,No,Weight Captured Separately,Freight Included in Commodity Cost,5284.04
10322,Zimbabwe,PMO - US,From RDC,N/A - From RDC,Truck,ARV,60,17465,113871.80,6.52,0.11,Yes,1392,Freight Included in Commodity Cost,134.03
10323,Zimbabwe,PMO - US,From RDC,N/A - From RDC,Truck,ARV,60,36639,72911.61,1.99,0.03,No,Weight Captured Separately,Freight Included in Commodity Cost,85.82

In [3]:
data.shape

(10324, 15)

In [4]:
data.head()

,Country,Managed By,Fulfill Via,Vendor INCO Term,Shipment Mode,Product Group,Unit of Measure (Per Pack),Line Item Quantity,Line Item Value,Pack Price,Unit Price,First Line Designation,Weight (Kilograms),Freight Cost (USD),Line Item Insurance (USD)
0,Côte d'Ivoire,PMO - US,Direct Drop,EXW,Air,HRDT,30,19,551.0,29.00,0.97,Yes,13,780.34,NaN
1,Vietnam,PMO - US,Direct Drop,EXW,Air,ARV,240,1000,6200.0,6.20,0.03,Yes,358,4521.5,NaN
2,Côte d'Ivoire,PMO - US,Direct Drop,FCA,Air,HRDT,100,500,40000.0,80.00,0.80,Yes,171,1653.78,NaN
3,Vietnam,PMO - US,Direct Drop,EXW,Air,ARV,60,31920,127360.8,3.99,0.07,Yes,1855,16007.06,NaN
4,Vietnam,PMO - US,Direct Drop,EXW,Air,ARV,60,38000,121600.0,3.20,0.05,Yes,7590,45450.08,NaN

In [5]:
data.tail()

,Country,Managed By,Fulfill Via,Vendor INCO Term,Shipment Mode,Product Group,Unit of Measure (Per Pack),Line Item Quantity,Line Item Value,Pack Price,Unit Price,First Line Designation,Weight (Kilograms),Freight Cost (USD),Line Item Insurance (USD)
10319,Zimbabwe,PMO - US,From RDC,N/A - From RDC,Truck,ARV,60,166571,599655.60,3.60,0.06,No,See DN-4307 (ID#:83920),See DN-4307 (ID#:83920),705.79
10320,Côte d'Ivoire,PMO - US,From RDC,N/A - From RDC,Truck,ARV,60,21072,137389.44,6.52,0.11,No,See DN-4313 (ID#:83921),See DN-4313 (ID#:83921),161.71
10321,Zambia,PMO - US,From RDC,N/A - From RDC,Truck,ARV,30,514526,5140114.74,9.99,0.33,No,Weight Captured Separately,Freight Included in Commodity Cost,5284.04
10322,Zimbabwe,PMO - US,From RDC,N/A - From RDC,Truck,ARV,60,17465,113871.80,6.52,0.11,Yes,1392,Freight Included in Commodity Cost,134.03
10323,Zimbabwe,PMO - US,From RDC,N/A - From RDC,Truck,ARV,60,36639,72911.61,1.99,0.03,No,Weight Captured Separately,Freight Included in Commodity Cost,85.82

In [6]:
data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 10324 entries, 0 to 10323
Data columns (total 15 columns):
Country                       10324 non-null object
Managed By                    10324 non-null object
Fulfill Via                   10324 non-null object
Vendor INCO Term              10324 non-null object
Shipment Mode                 9964 non-null object
Product Group                 10324 non-null object
Unit of Measure (Per Pack)    10324 non-null int64
Line Item Quantity            10324 non-null int64
Line Item Value               10324 non-null float64
Pack Price                    10324 non-null float64
Unit Price                    10324 non-null float64
First Line Designation        10324 non-null object
Weight (Kilograms)            10324 non-null object
Freight Cost (USD)            10324 non-null object
Line Item Insurance (USD)     10037 non-null float64
dtypes: float64(4), int64(2), object(9)
memory usage: 1.2+ MB

In [7]:
data.isna().sum()

Country                         0
Managed By                      0
Fulfill Via                     0
Vendor INCO Term                0
Shipment Mode                 360
Product Group                   0
Unit of Measure (Per Pack)      0
Line Item Quantity              0
Line Item Value                 0
Pack Price                      0
Unit Price                      0
First Line Designation          0
Weight (Kilograms)              0
Freight Cost (USD)              0
Line Item Insurance (USD)     287
dtype: int64

In [8]:
data.columns

Index(['Country', 'Managed By', 'Fulfill Via', 'Vendor INCO Term',
       'Shipment Mode', 'Product Group', 'Unit of Measure (Per Pack)',
       'Line Item Quantity', 'Line Item Value', 'Pack Price', 'Unit Price',
       'First Line Designation', 'Weight (Kilograms)', 'Freight Cost (USD)',
       'Line Item Insurance (USD)'],
      dtype='object')

In [9]:
data.describe()

,Unit of Measure (Per Pack),Line Item Quantity,Line Item Value,Pack Price,Unit Price,Line Item Insurance (USD)
count,10324.000000,10324.000000,1.032400e+04,10324.000000,10324.000000,10037.000000
mean,77.990895,18332.534870,1.576506e+05,21.910241,0.611701,240.117626
std,76.579764,40035.302961,3.452921e+05,45.609223,3.275808,500.190568
min,1.000000,1.000000,0.000000e+00,0.000000,0.000000,0.000000
25%,30.000000,408.000000,4.314593e+03,4.120000,0.080000,6.510000
50%,60.000000,3000.000000,3.047147e+04,9.300000,0.160000,47.040000
75%,90.000000,17039.750000,1.664471e+05,23.592500,0.470000,252.400000
max,1000.000000,619999.000000,5.951990e+06,1345.640000,238.650000,7708.440000

#  Data Cleaning

# Checking for Duplicates in a dataset

In [10]:
data.duplicated().sum()

120

In [11]:
data['Shipment Mode'].value_counts()

Air            6113
Truck          2830
Air Charter     650
Ocean           371
Name: Shipment Mode, dtype: int64

# We can see that shipment mode Air is the mostly used So we can fill the null values with 'Air"

In [12]:
data['Shipment Mode'].fillna('Air',inplace=True)

In [13]:
data['Shipment Mode'].isnull().sum()

0

In [14]:
data

,Country,Managed By,Fulfill Via,Vendor INCO Term,Shipment Mode,Product Group,Unit of Measure (Per Pack),Line Item Quantity,Line Item Value,Pack Price,Unit Price,First Line Designation,Weight (Kilograms),Freight Cost (USD),Line Item Insurance (USD)
0,Côte d'Ivoire,PMO - US,Direct Drop,EXW,Air,HRDT,30,19,551.00,29.00,0.97,Yes,13,780.34,NaN
1,Vietnam,PMO - US,Direct Drop,EXW,Air,ARV,240,1000,6200.00,6.20,0.03,Yes,358,4521.5,NaN
2,Côte d'Ivoire,PMO - US,Direct Drop,FCA,Air,HRDT,100,500,40000.00,80.00,0.80,Yes,171,1653.78,NaN
3,Vietnam,PMO - US,Direct Drop,EXW,Air,ARV,60,31920,127360.80,3.99,0.07,Yes,1855,16007.06,NaN
4,Vietnam,PMO - US,Direct Drop,EXW,Air,ARV,60,38000,121600.00,3.20,0.05,Yes,7590,45450.08,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
10319,Zimbabwe,PMO - US,From RDC,N/A - From RDC,Truck,ARV,60,166571,599655.60,3.60,0.06,No,See DN-4307 (ID#:83920),See DN-4307 (ID#:83920),705.79
10320,Côte d'Ivoire,PMO - US,From RDC,N/A - From RDC,Truck,ARV,60,21072,137389.44,6.52,0.11,No,See DN-4313 (ID#:83921),See DN-4313 (ID#:83921),161.71
10321,Zambia,PMO - US,From RDC,N/A - From RDC,Truck,ARV,30,514526,5140114.74,9.99,0.33,No,Weight Captured Separately,Freight Included in Commodity Cost,5284.04
10322,Zimbabwe,PMO - US,From RDC,N/A - From RDC,Truck,ARV,60,17465,113871.80,6.52,0.11,Yes,1392,Freight Included in Commodity Cost,134.03
10323,Zimbabwe,PMO - US,From RDC,N/A - From RDC,Truck,ARV,60,36639,72911.61,1.99,0.03,No,Weight Captured Separately,Freight Included in Commodity Cost,85.82

In [15]:
#Replacing the other null records with NA
data.fillna('NA',inplace=True)
data

,Country,Managed By,Fulfill Via,Vendor INCO Term,Shipment Mode,Product Group,Unit of Measure (Per Pack),Line Item Quantity,Line Item Value,Pack Price,Unit Price,First Line Designation,Weight (Kilograms),Freight Cost (USD),Line Item Insurance (USD)
0,Côte d'Ivoire,PMO - US,Direct Drop,EXW,Air,HRDT,30,19,551.00,29.00,0.97,Yes,13,780.34,NA
1,Vietnam,PMO - US,Direct Drop,EXW,Air,ARV,240,1000,6200.00,6.20,0.03,Yes,358,4521.5,NA
2,Côte d'Ivoire,PMO - US,Direct Drop,FCA,Air,HRDT,100,500,40000.00,80.00,0.80,Yes,171,1653.78,NA
3,Vietnam,PMO - US,Direct Drop,EXW,Air,ARV,60,31920,127360.80,3.99,0.07,Yes,1855,16007.06,NA
4,Vietnam,PMO - US,Direct Drop,EXW,Air,ARV,60,38000,121600.00,3.20,0.05,Yes,7590,45450.08,NA
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
10319,Zimbabwe,PMO - US,From RDC,N/A - From RDC,Truck,ARV,60,166571,599655.60,3.60,0.06,No,See DN-4307 (ID#:83920),See DN-4307 (ID#:83920),705.79
10320,Côte d'Ivoire,PMO - US,From RDC,N/A - From RDC,Truck,ARV,60,21072,137389.44,6.52,0.11,No,See DN-4313 (ID#:83921),See DN-4313 (ID#:83921),161.71
10321,Zambia,PMO - US,From RDC,N/A - From RDC,Truck,ARV,30,514526,5140114.74,9.99,0.33,No,Weight Captured Separately,Freight Included in Commodity Cost,5284.04
10322,Zimbabwe,PMO - US,From RDC,N/A - From RDC,Truck,ARV,60,17465,113871.80,6.52,0.11,Yes,1392,Freight Included in Commodity Cost,134.03
10323,Zimbabwe,PMO - US,From RDC,N/A - From RDC,Truck,ARV,60,36639,72911.61,1.99,0.03,No,Weight Captured Separately,Freight Included in Commodity Cost,85.82

In [16]:
data.isna().sum()

Country                       0
Managed By                    0
Fulfill Via                   0
Vendor INCO Term              0
Shipment Mode                 0
Product Group                 0
Unit of Measure (Per Pack)    0
Line Item Quantity            0
Line Item Value               0
Pack Price                    0
Unit Price                    0
First Line Designation        0
Weight (Kilograms)            0
Freight Cost (USD)            0
Line Item Insurance (USD)     0
dtype: int64

#  Categorizing Numerical and categorical columns

In [17]:
qual=[]
quan=[]
for columnname in data.columns:
    #print(columnname)
    if (data[columnname].dtype=='O'):
        #print("Qual")
        qual.append(columnname)
    else:
        #print("Quant")
        quan.append(columnname)

In [18]:
qual

['Country',
 'Managed By',
 'Fulfill Via',
 'Vendor INCO Term',
 'Shipment Mode',
 'Product Group',
 'First Line Designation',
 'Weight (Kilograms)',
 'Freight Cost (USD)',
 'Line Item Insurance (USD)']

In [19]:
quan

['Unit of Measure (Per Pack)',
 'Line Item Quantity',
 'Line Item Value',
 'Pack Price',
 'Unit Price']

#   Changing the datatype of the columns Freight Cost,Line item insurance

In [20]:
data['Freight Cost (USD)'].value_counts()

Freight Included in Commodity Cost    1442
Invoiced Separately                    239
9736.1                                  36
6147.18                                 27
7445.8                                  16
                                      ...
4969.95                                  1
28541.79                                 1
1765.18                                  1
See ASN-30940 (ID#:51233)                1
See DN-3155 (ID#:84260)                  1
Name: Freight Cost (USD), Length: 6733, dtype: int64

In [21]:
data['Freight Cost (USD)'] = pd.to_numeric(data['Freight Cost (USD)'], errors='coerce')
#Since there are more alphanumberic characters we are converting it into numeric

In [22]:
data.head()

,Country,Managed By,Fulfill Via,Vendor INCO Term,Shipment Mode,Product Group,Unit of Measure (Per Pack),Line Item Quantity,Line Item Value,Pack Price,Unit Price,First Line Designation,Weight (Kilograms),Freight Cost (USD),Line Item Insurance (USD)
0,Côte d'Ivoire,PMO - US,Direct Drop,EXW,Air,HRDT,30,19,551.0,29.00,0.97,Yes,13,780.34,NA
1,Vietnam,PMO - US,Direct Drop,EXW,Air,ARV,240,1000,6200.0,6.20,0.03,Yes,358,4521.50,NA
2,Côte d'Ivoire,PMO - US,Direct Drop,FCA,Air,HRDT,100,500,40000.0,80.00,0.80,Yes,171,1653.78,NA
3,Vietnam,PMO - US,Direct Drop,EXW,Air,ARV,60,31920,127360.8,3.99,0.07,Yes,1855,16007.06,NA
4,Vietnam,PMO - US,Direct Drop,EXW,Air,ARV,60,38000,121600.0,3.20,0.05,Yes,7590,45450.08,NA

In [23]:
data['Weight (Kilograms)'] = pd.to_numeric(data['Weight (Kilograms)'], errors='coerce')

In [24]:
data['Weight (Kilograms)'].value_counts()

2.0       29
6.0       26
1.0       23
60.0      20
5.0       20
          ..
2672.0     1
193.0      1
3536.0     1
892.0      1
3349.0     1
Name: Weight (Kilograms), Length: 3388, dtype: int64

In [25]:
data['Line Item Insurance (USD)'] = pd.to_numeric(data['Line Item Insurance (USD)'], errors='coerce')

In [26]:
data['Line Item Insurance (USD)'].value_counts()

0.00      54
0.02      37
0.07      33
0.06      30
0.05      30
          ..
84.08      1
423.40     1
88.48      1
362.68     1
126.71     1
Name: Line Item Insurance (USD), Length: 6722, dtype: int64

In [27]:
data.head(10)

,Country,Managed By,Fulfill Via,Vendor INCO Term,Shipment Mode,Product Group,Unit of Measure (Per Pack),Line Item Quantity,Line Item Value,Pack Price,Unit Price,First Line Designation,Weight (Kilograms),Freight Cost (USD),Line Item Insurance (USD)
0,Côte d'Ivoire,PMO - US,Direct Drop,EXW,Air,HRDT,30,19,551.00,29.00,0.97,Yes,13.0,780.34,NaN
1,Vietnam,PMO - US,Direct Drop,EXW,Air,ARV,240,1000,6200.00,6.20,0.03,Yes,358.0,4521.50,NaN
2,Côte d'Ivoire,PMO - US,Direct Drop,FCA,Air,HRDT,100,500,40000.00,80.00,0.80,Yes,171.0,1653.78,NaN
3,Vietnam,PMO - US,Direct Drop,EXW,Air,ARV,60,31920,127360.80,3.99,0.07,Yes,1855.0,16007.06,NaN
4,Vietnam,PMO - US,Direct Drop,EXW,Air,ARV,60,38000,121600.00,3.20,0.05,Yes,7590.0,45450.08,NaN
5,Nigeria,PMO - US,Direct Drop,EXW,Air,ARV,240,416,2225.60,5.35,0.02,Yes,504.0,5920.42,NaN
6,Zambia,PMO - US,Direct Drop,DDU,Air,ARV,90,135,4374.00,32.40,0.36,Yes,328.0,NaN,NaN
7,Tanzania,PMO - US,Direct Drop,EXW,Air,ARV,60,16667,60834.55,3.65,0.06,Yes,1478.0,6212.41,NaN
8,Nigeria,PMO - US,Direct Drop,EXW,Air,ARV,60,273,532.35,1.95,0.03,No,NaN,NaN,NaN
9,Zambia,PMO - US,Direct Drop,CIP,Air,ARV,120,2800,115080.00,41.10,0.34,Yes,643.0,NaN,NaN

In [28]:
# To fill the Median value of the freight cost column
median_value = data['Freight Cost (USD)'].median()
median_value

5869.655000000001

In [29]:
data['Freight Cost (USD)'].fillna(median_value,inplace=True)

In [30]:
median_weight = data['Weight (Kilograms)'].median()
data['Weight (Kilograms)'].fillna(median_weight,inplace=True)

In [31]:
median_life = data['Line Item Insurance (USD)'].median()
data['Line Item Insurance (USD)'].fillna(median_life,inplace=True)

In [32]:
data.head()

,Country,Managed By,Fulfill Via,Vendor INCO Term,Shipment Mode,Product Group,Unit of Measure (Per Pack),Line Item Quantity,Line Item Value,Pack Price,Unit Price,First Line Designation,Weight (Kilograms),Freight Cost (USD),Line Item Insurance (USD)
0,Côte d'Ivoire,PMO - US,Direct Drop,EXW,Air,HRDT,30,19,551.0,29.00,0.97,Yes,13.0,780.34,47.04
1,Vietnam,PMO - US,Direct Drop,EXW,Air,ARV,240,1000,6200.0,6.20,0.03,Yes,358.0,4521.50,47.04
2,Côte d'Ivoire,PMO - US,Direct Drop,FCA,Air,HRDT,100,500,40000.0,80.00,0.80,Yes,171.0,1653.78,47.04
3,Vietnam,PMO - US,Direct Drop,EXW,Air,ARV,60,31920,127360.8,3.99,0.07,Yes,1855.0,16007.06,47.04
4,Vietnam,PMO - US,Direct Drop,EXW,Air,ARV,60,38000,121600.0,3.20,0.05,Yes,7590.0,45450.08,47.04

In [33]:
data.dtypes

Country                        object
Managed By                     object
Fulfill Via                    object
Vendor INCO Term               object
Shipment Mode                  object
Product Group                  object
Unit of Measure (Per Pack)      int64
Line Item Quantity              int64
Line Item Value               float64
Pack Price                    float64
Unit Price                    float64
First Line Designation         object
Weight (Kilograms)            float64
Freight Cost (USD)            float64
Line Item Insurance (USD)     float64
dtype: object

In [34]:
data.isna().sum()

Country                       0
Managed By                    0
Fulfill Via                   0
Vendor INCO Term              0
Shipment Mode                 0
Product Group                 0
Unit of Measure (Per Pack)    0
Line Item Quantity            0
Line Item Value               0
Pack Price                    0
Unit Price                    0
First Line Designation        0
Weight (Kilograms)            0
Freight Cost (USD)            0
Line Item Insurance (USD)     0
dtype: int64

In [35]:
import pandas as pd
from sklearn.preprocessing import LabelEncoder
encoder = LabelEncoder()
data["Country_Encoded"] = encoder.fit_transform(data["Country"])

In [36]:
data

,Country,Managed By,Fulfill Via,Vendor INCO Term,Shipment Mode,Product Group,Unit of Measure (Per Pack),Line Item Quantity,Line Item Value,Pack Price,Unit Price,First Line Designation,Weight (Kilograms),Freight Cost (USD),Line Item Insurance (USD),Country_Encoded
0,Côte d'Ivoire,PMO - US,Direct Drop,EXW,Air,HRDT,30,19,551.00,29.00,0.97,Yes,13.0,780.340,47.04,9
1,Vietnam,PMO - US,Direct Drop,EXW,Air,ARV,240,1000,6200.00,6.20,0.03,Yes,358.0,4521.500,47.04,40
2,Côte d'Ivoire,PMO - US,Direct Drop,FCA,Air,HRDT,100,500,40000.00,80.00,0.80,Yes,171.0,1653.780,47.04,9
3,Vietnam,PMO - US,Direct Drop,EXW,Air,ARV,60,31920,127360.80,3.99,0.07,Yes,1855.0,16007.060,47.04,40
4,Vietnam,PMO - US,Direct Drop,EXW,Air,ARV,60,38000,121600.00,3.20,0.05,Yes,7590.0,45450.080,47.04,40
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
10319,Zimbabwe,PMO - US,From RDC,N/A - From RDC,Truck,ARV,60,166571,599655.60,3.60,0.06,No,1047.0,5869.655,705.79,42
10320,Côte d'Ivoire,PMO - US,From RDC,N/A - From RDC,Truck,ARV,60,21072,137389.44,6.52,0.11,No,1047.0,5869.655,161.71,9
10321,Zambia,PMO - US,From RDC,N/A - From RDC,Truck,ARV,30,514526,5140114.74,9.99,0.33,No,1047.0,5869.655,5284.04,41
10322,Zimbabwe,PMO - US,From RDC,N/A - From RDC,Truck,ARV,60,17465,113871.80,6.52,0.11,Yes,1392.0,5869.655,134.03,42
10323,Zimbabwe,PMO - US,From RDC,N/A - From RDC,Truck,ARV,60,36639,72911.61,1.99,0.03,No,1047.0,5869.655,85.82,42

In [37]:
df=data.copy()

In [38]:
df

,Country,Managed By,Fulfill Via,Vendor INCO Term,Shipment Mode,Product Group,Unit of Measure (Per Pack),Line Item Quantity,Line Item Value,Pack Price,Unit Price,First Line Designation,Weight (Kilograms),Freight Cost (USD),Line Item Insurance (USD),Country_Encoded
0,Côte d'Ivoire,PMO - US,Direct Drop,EXW,Air,HRDT,30,19,551.00,29.00,0.97,Yes,13.0,780.340,47.04,9
1,Vietnam,PMO - US,Direct Drop,EXW,Air,ARV,240,1000,6200.00,6.20,0.03,Yes,358.0,4521.500,47.04,40
2,Côte d'Ivoire,PMO - US,Direct Drop,FCA,Air,HRDT,100,500,40000.00,80.00,0.80,Yes,171.0,1653.780,47.04,9
3,Vietnam,PMO - US,Direct Drop,EXW,Air,ARV,60,31920,127360.80,3.99,0.07,Yes,1855.0,16007.060,47.04,40
4,Vietnam,PMO - US,Direct Drop,EXW,Air,ARV,60,38000,121600.00,3.20,0.05,Yes,7590.0,45450.080,47.04,40
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
10319,Zimbabwe,PMO - US,From RDC,N/A - From RDC,Truck,ARV,60,166571,599655.60,3.60,0.06,No,1047.0,5869.655,705.79,42
10320,Côte d'Ivoire,PMO - US,From RDC,N/A - From RDC,Truck,ARV,60,21072,137389.44,6.52,0.11,No,1047.0,5869.655,161.71,9
10321,Zambia,PMO - US,From RDC,N/A - From RDC,Truck,ARV,30,514526,5140114.74,9.99,0.33,No,1047.0,5869.655,5284.04,41
10322,Zimbabwe,PMO - US,From RDC,N/A - From RDC,Truck,ARV,60,17465,113871.80,6.52,0.11,Yes,1392.0,5869.655,134.03,42
10323,Zimbabwe,PMO - US,From RDC,N/A - From RDC,Truck,ARV,60,36639,72911.61,1.99,0.03,No,1047.0,5869.655,85.82,42

#  Descriptive Statistics

In [67]:
qual=[]
quan=[]
for columnname in df.columns:
    #print(columnname)
    if (df[columnname].dtype=='O'):
        #print("Qual")
        qual.append(columnname)
    else:
        #print("Quant")
        quan.append(columnname)

In [68]:
qual

['Country',
 'Managed By',
 'Fulfill Via',
 'Vendor INCO Term',
 'Shipment Mode',
 'Product Group',
 'First Line Designation']

In [69]:
quan

['Unit of Measure (Per Pack)',
 'Line Item Quantity',
 'Line Item Value',
 'Pack Price',
 'Unit Price',
 'Weight (Kilograms)',
 'Freight Cost (USD)',
 'Line Item Insurance (USD)',
 'Country_Encoded']

In [70]:
descriptive=pd.DataFrame(index=["Mean","Median","Mode","Q1:25%","Q2:50%","Q3:75%","99%","Q4:100%","IQR","1.5Rule",
                                "Lesser","Greater","Min","Max","kurtosis","skewness","Variance","Standard deviation"],columns=quan)
for columnname in quan:
    descriptive[columnname]["Mean"]=df[columnname].mean()
    descriptive[columnname]["Median"]=df[columnname].median()
    descriptive[columnname]["Mode"]=df[columnname].mode()[0]
    descriptive[columnname]["Q1:25%"]=df.describe()[columnname]["25%"]
    descriptive[columnname]["Q2:50%"]=df.describe()[columnname]["50%"]
    descriptive[columnname]["Q3:75%"]=df.describe()[columnname]["75%"]
    descriptive[columnname]["99%"]=np.percentile(df[columnname],99)
    descriptive[columnname]["Q4:100%"]=df.describe()[columnname]["max"]
    descriptive[columnname]["IQR"]=descriptive[columnname]["Q3:75%"]-descriptive[columnname]["Q1:25%"]
    descriptive[columnname]["1.5Rule"]=1.5*descriptive[columnname]["IQR"]
    descriptive[columnname]["Lesser"]=descriptive[columnname]["Q1:25%"]-descriptive[columnname]["1.5Rule"]
    descriptive[columnname]["Greater"]=descriptive[columnname]["Q3:75%"]+descriptive[columnname]["1.5Rule"]
    descriptive[columnname]["Min"]=df[columnname].min()
    descriptive[columnname]["Max"]=df[columnname].max()
    descriptive[columnname]["kurtosis"]=df[columnname].kurtosis()
    descriptive[columnname]["skewness"]=df[columnname].skew()
    descriptive[columnname]["Variance"]=df[columnname].var()
    descriptive[columnname]["Standard deviation"]=df[columnname].std()

In [71]:
descriptive

,Unit of Measure (Per Pack),Line Item Quantity,Line Item Value,Pack Price,Unit Price,Weight (Kilograms),Freight Cost (USD),Line Item Insurance (USD),Country_Encoded
Mean,69.2972,11163.2,105691,16.3058,0.320711,1272.45,6398.18,155.372,27.4805
Median,60,3000,30471.5,9.3,0.16,1047,5869.66,47.04,30
Mode,60,41987.4,409646,52.8013,1.055,1047,5869.66,593.83,33
Q1:25%,30,408,4314.59,4.12,0.08,617,4323.81,7.03,16
Q2:50%,60,3000,30471.5,9.3,0.16,1047,5869.66,47.04,30
Q3:75%,90,17039.8,166447,23.5925,0.47,1596.5,7707.64,241.75,39
99%,180,41987.4,409646,52.8013,1.055,3065.75,12783.4,593.83,42
Q4:100%,180,41987.4,409646,52.8013,1.055,3065.75,12783.4,593.83,42
IQR,60,16631.8,162133,19.4725,0.39,979.5,3383.83,234.72,23
1.5Rule,90,24947.6,243199,29.2088,0.585,1469.25,5075.75,352.08,34.5
Lesser,-60,-24539.6,-238884,-25.0888,-0.505,-852.25,-751.941,-345.05,-18.5
Greater,180,41987.4,409646,52.8013,1.055,3065.75,12783.4,593.83,73.5
Min,1,1,0,0,0,0,0.75,0,0
Max,180,41987.4,409646,52.8013,1.055,3065.75,12783.4,593.83,42
kurtosis,0.801815,-0.0983783,0.11307,0.238751,-0.150919,-0.540543,-0.605687,0.0528294,-1.09777
skewness,1.27036,1.22615,1.25514,1.23727,1.12702,0.776899,0.463709,1.24237,-0.524448
Variance,2154.59,2.24733e+08,1.93897e+10,268.664,0.11117,962350,1.36686e+07,41417.6,136.697
Standard deviation,46.4176,14991.1,139247,16.391,0.333422,980.994,3697.11,203.513,11.6918

# Handling Outliers

In [72]:
lesser=[]
greater=[]
for colname in quan:
    if(descriptive[colname]["Min"]<descriptive[colname]["Lesser"]):
        lesser.append(colname)
    if(descriptive[colname]["Max"]>descriptive[colname]["Greater"]):
        greater.append(colname)

In [73]:
greater

[]

In [74]:
lesser

[]

In [60]:
def insertoutlier(data,greater):
    for columnName in greater:
        data[columnName][data[columnName]>descriptive[columnName]["Greater"]]=descriptive[columnName]["Greater"]
    return data

In [61]:
insertoutlier(df,greater)

C:\Users\MOHANLAL\anaconda3\envs\aiml\lib\site-packages\ipykernel_launcher.py:3: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  This is separate from the ipykernel package so we can avoid doing imports until

,Country,Managed By,Fulfill Via,Vendor INCO Term,Shipment Mode,Product Group,Unit of Measure (Per Pack),Line Item Quantity,Line Item Value,Pack Price,Unit Price,First Line Designation,Weight (Kilograms),Freight Cost (USD),Line Item Insurance (USD),Country_Encoded
0,Côte d'Ivoire,PMO - US,Direct Drop,EXW,Air,HRDT,30,19.000,551.00000,29.00000,0.97,Yes,13.00,780.34000,47.04,9
1,Vietnam,PMO - US,Direct Drop,EXW,Air,ARV,180,1000.000,6200.00000,6.20000,0.03,Yes,358.00,4521.50000,47.04,40
2,Côte d'Ivoire,PMO - US,Direct Drop,FCA,Air,HRDT,100,500.000,40000.00000,52.80125,0.80,Yes,171.00,1653.78000,47.04,9
3,Vietnam,PMO - US,Direct Drop,EXW,Air,ARV,60,31920.000,127360.80000,3.99000,0.07,Yes,1855.00,12783.38875,47.04,40
4,Vietnam,PMO - US,Direct Drop,EXW,Air,ARV,60,38000.000,121600.00000,3.20000,0.05,Yes,3065.75,12783.38875,47.04,40
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
10319,Zimbabwe,PMO - US,From RDC,N/A - From RDC,Truck,ARV,60,41987.375,409645.96125,3.60000,0.06,No,1047.00,5869.65500,593.83,42
10320,Côte d'Ivoire,PMO - US,From RDC,N/A - From RDC,Truck,ARV,60,21072.000,137389.44000,6.52000,0.11,No,1047.00,5869.65500,161.71,9
10321,Zambia,PMO - US,From RDC,N/A - From RDC,Truck,ARV,30,41987.375,409645.96125,9.99000,0.33,No,1047.00,5869.65500,593.83,41
10322,Zimbabwe,PMO - US,From RDC,N/A - From RDC,Truck,ARV,60,17465.000,113871.80000,6.52000,0.11,Yes,1392.00,5869.65500,134.03,42
10323,Zimbabwe,PMO - US,From RDC,N/A - From RDC,Truck,ARV,60,36639.000,72911.61000,1.99000,0.03,No,1047.00,5869.65500,85.82,42

In [77]:
# Assuming 'quan' is defined somewhere in your code
descriptive = pd.DataFrame(index=['mean','median','mode','Q1:25%','Q2:50%','Q3:75%','Q4:100%','IQR','1.5rule','lesser','greater','min','max'], columns=quan)

# Assuming 'dataset' is your DataFrame
for ColumnName in quan:
    descriptive.loc['mean', ColumnName] = df[ColumnName].mean()
    descriptive.loc['median', ColumnName] = df[ColumnName].median()
    descriptive.loc['mode', ColumnName] = df[ColumnName].mode()[0]
    descriptive.loc['Q1:25%', ColumnName] = df[ColumnName].quantile(0.25)
    descriptive.loc['Q2:50%', ColumnName] = df[ColumnName].quantile(0.50)
    descriptive.loc['Q3:75%', ColumnName] = df[ColumnName].quantile(0.75)
    descriptive.loc['99%', ColumnName] = np.percentile(df[ColumnName], 99)
    descriptive.loc['Q4:100%', ColumnName] = df[ColumnName].max()
    descriptive.loc['IQR', ColumnName] = descriptive.loc['Q3:75%', ColumnName] - descriptive.loc['Q1:25%', ColumnName]
    descriptive.loc['1.5rule', ColumnName] = 1.5 * descriptive.loc['IQR', ColumnName]
    descriptive.loc['lesser', ColumnName] = descriptive.loc['Q1:25%', ColumnName] - descriptive.loc['1.5rule', ColumnName]
    descriptive.loc['greater', ColumnName] = descriptive.loc['Q3:75%', ColumnName] + descriptive.loc['1.5rule', ColumnName]
    descriptive.loc['min', ColumnName] = df[ColumnName].min()
    descriptive.loc['max', ColumnName] = df[ColumnName].max()

In [78]:
def find_outliers(quan):
    lesser = []
    greater = []
    
    for columnName in quan:
        if descriptive[columnName]["min"] < descriptive[columnName]["lesser"]:
            lesser.append(columnName)
        if descriptive[columnName]["max"] > descriptive[columnName]["greater"]:
            greater.append(columnName)
    
    return lesser, greater

In [79]:
find_outliers(quan)

([], [])

In [80]:
lesser, greater=find_outliers(quan)

In [81]:
lesser

[]

In [82]:
greater

[]

#  There are no outliers present in the dataset

In [83]:
df.to_csv('clean_data.csv',index=False)